// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1mzoDAuYCi97VD-F6jLeUtjUASuLiaVU',
    appId: '1:924131185521:android:cebe07431e2a97f97a5cd0',
    messagingSenderId: '924131185521',
    projectId: 'cocoa-master',
    storageBucket: 'cocoa-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD1ZgOgeMW0wooyfp0XfrVAZYX7puTHAs',
    appId: '1:924131185521:ios:737c89761ee395757a5cd0',
    messagingSenderId: '924131185521',
    projectId: 'cocoa-master',
    storageBucket: 'cocoa-master.appspot.com',
    androidClientId: '924131185521-9l6b0vbp9h90ojo2dh81ufsm2gn2fnd7.apps.googleusercontent.com',
    iosClientId: '924131185521-raprqdabc10fn6pl8ec4ujab81p47gal.apps.googleusercontent.com',
    iosBundleId: 'com.afarinick.cj.cocoamaster',
  );
}
